/* SPDX-License-Identifier: Apache-2.0 */
#ifndef BRICKWRIGHT_PSA_CRYPTO_NUTTX_CONFIG_H
#define BRICKWRIGHT_PSA_CRYPTO_NUTTX_CONFIG_H

#define PSA_WANT_KEY_TYPE_AES 1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_BASIC 1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_IMPORT 1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_EXPORT 1
#define PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY 1
#define PSA_WANT_ALG_ECB_NO_PADDING 1
#define PSA_WANT_ALG_CMAC 1
#define PSA_WANT_ALG_ECDH 1
#define PSA_WANT_ECC_SECP_R1_256 1

#endif
