/* SPDX-License-Identifier: Apache-2.0 */
#ifndef BRICKWRIGHT_ZEPHYR_AUTOCONF_H
#define BRICKWRIGHT_ZEPHYR_AUTOCONF_H
#define CONFIG_NET_BUF_ALIGNMENT 0
#define CONFIG_NET_BUF_LOG_LEVEL 0
#define CONFIG_NET_BUF_POOL_USAGE 1

#define CONFIG_BT_HCI_HOST 1
#define CONFIG_BT_CONN 1
#define CONFIG_BT_CONN_TX 1
#define CONFIG_BT_CONN_FRAG_COUNT CONFIG_BT_BUF_ACL_TX_COUNT
#define CONFIG_BT_BROADCASTER 1
#define CONFIG_BT_OBSERVER 1
#define CONFIG_BT_PERIPHERAL 1
#define CONFIG_BT_CENTRAL 1
#define CONFIG_BT_CLASSIC 1
#define CONFIG_BT_RFCOMM 1
#define CONFIG_BT_SMP 1
#define CONFIG_BT_HOST_CRYPTO 1
#define CONFIG_BT_SETTINGS 1
#define CONFIG_BT_BONDABLE 1
#define CONFIG_BT_RECV_WORKQ_SYS 1
#define CONFIG_BT_DEVICE_NAME "Brickwright SPIKE"
#define CONFIG_BT_DEVICE_APPEARANCE 0
#define CONFIG_BT_LIM_ADV_TIMEOUT 30
#define CONFIG_BT_MAX_PAIRED 1
#define CONFIG_BT_SETTINGS_CCC_STORE_MAX 1
#define CONFIG_BT_BR_MIN_ENC_KEY_SIZE 7
#define CONFIG_BT_SMP_MIN_ENC_KEY_SIZE 7
#define CONFIG_BT_BACKGROUND_SCAN_INTERVAL 2048
#define CONFIG_BT_BACKGROUND_SCAN_WINDOW 18
#define CONFIG_BT_COD 0
#define CONFIG_BT_PAGE_TIMEOUT 0x2000
#define CONFIG_BT_LIMITED_DISCOVERABLE_DURATION 60
/* Two pointers: 8 bytes on Cortex-M4 and 16 bytes in the 64-bit host harness. */
#define CONFIG_BT_CONN_TX_USER_DATA_SIZE 16
#define CONFIG_BT_ATT_PREPARE_COUNT 0
#define CONFIG_BT_ATT_TX_COUNT CONFIG_BT_BUF_ACL_TX_COUNT
#define CONFIG_BT_L2CAP_TX_BUF_COUNT CONFIG_BT_BUF_ACL_TX_COUNT
#define CONFIG_BT_RFCOMM_L2CAP_MTU CONFIG_BT_BUF_ACL_RX_SIZE
#define CONFIG_BT_L2CAP_TX_MTU 253
#define CONFIG_BT_L2CAP_DYNAMIC_CHANNEL 1
#define CONFIG_BT_MAX_SCO_CONN 1
#define CONFIG_BT_L2CAP_RX_FLUSH_TO 0xffff
#define CONFIG_BT_L2CAP_CONN_RTX_TIMEOUT 40
#define CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT 5000
#define CONFIG_BT_CREATE_CONN_TIMEOUT 3

#define CONFIG_BT_BUF_ACL_RX_SIZE 260
#define CONFIG_BT_BUF_ACL_RX_COUNT 6
#define CONFIG_BT_BUF_ACL_RX_COUNT_EXTRA 2
#define CONFIG_BT_BUF_ACL_TX_COUNT 6
#define CONFIG_BT_BUF_CMD_TX_COUNT 2
#define CONFIG_BT_BUF_CMD_TX_SIZE 255
#define CONFIG_BT_BUF_EVT_RX_COUNT 8
#define CONFIG_BT_BUF_EVT_RX_SIZE 255
#define CONFIG_BT_BUF_EVT_DISCARDABLE_COUNT 2
#define CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE 255
#define CONFIG_BT_BUF_SYNC_EVT_POOL_COUNT 1
#define CONFIG_BT_ID_MAX 1
#define CONFIG_BT_MAX_CONN 2
#define CONFIG_BT_EXT_ADV_MAX_ADV_SET 1
#define CONFIG_BT_PER_ADV_SYNC_BUF_SIZE 0
#define CONFIG_BT_LONG_WQ 1
#define CONFIG_BT_LONG_WQ_STACK_SIZE 1536
#define CONFIG_BT_LONG_WQ_PRIO 10
#define CONFIG_BT_LONG_WQ_INIT_PRIO 50
#define CONFIG_BRICKWRIGHT_DELAYED_WORK_SLOTS 8
#endif
